### ISSUE TITLE
Cluster nodes UI broken since 0.28.0

### ISSUE THREAD

**Issue by Munchungus** [BeryJu/gravity#1949]
**Describe the bug**
Cluster nodes page doesn't load and just displays the spinning loading circle. After trying different versions it looks like this change occurred between 0.27.1 and 0.28.0. I see a 404 in the browser and in the logs for the '/api/v1/etcd/members' endpoint and I see changes affecting this endpoint in f3e3ef3 so may be this is the root cause?

**To Reproduce**

1. Start Gravity 0.28.0 or newer
2. Go to 'Cluster -> Nodes'
3. Node info is not loaded

**Expected behavior**
Cluster node info should load.

**Screenshots**

<img width="1071" height="476" alt="Image" src="https://github.com/user-attachments/assets/d7326508-3896-410e-9377-5990a13ff4c1" />

<img width="338" height="200" alt="Image" src="https://github.com/user-attachments/assets/83616ebc-0b8a-43fa-a3d0-31737d8ce9e3" />

**Logs**
```
{"level":"info","ts":1763302062.3391793,"logger":"role.api","msg":"HTTP Request","instance":"gravity-6d87444dc6-zxtlz","version":"0.28.0","host":"gravity.example.com","remote":"10.255.1.132:57664","runtime":0,"method":"GET","size":19,"status":404,"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:145.0) Gecko/20100101 Firefox/145.0","url":"/api/v1/etcd/members","user":"REDACTED"}
```

**Version and Deployment (please complete the following information):**

-   Gravity version: 0.28.0 onwards
-   Deployment: kubernetes deployment with external etcd

**Additional context**

**Comment by BeryJu** [comment]
This is fixed on main (since 0.29, not exactly sure which commit fixed it but yeah there were some issues with the api client generation for the UI)

**Comment by Munchungus** [comment]
I'm still seeing the issue on versions 0.29.0 up to the latest 0.32.1. Just to reiterate I'm running Gravity connected to an external etcd cluster instead of the built in etcd, I haven't tested it with the built in etcd.
